name: Code CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

concurrency:
  group: code-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  v-compiles-vee-examples:
    runs-on: ubuntu-18.04
    timeout-minutes: 30
    env:
      VFLAGS: -cc tcc -no-retry-compilation
    steps:
      - name: Install V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - name: Checkout vee
        uses: actions/checkout@v2
        with:
          path: vee

      - name: Link local SDL folder in ~/.vmodules/vee
        run: |
          cd vee
          mkdir -p ~/.vmodules
          ln -s $(pwd) ~/.vmodules/vee

      - name: Test code formatting
        run: |
          cd vee
          v test-fmt

      - name: Build vee shared
        run: v -shared -g vee

      - name: Run tests
        run: v test vee

      - name: Build vee examples
        run: |
          v should-compile-all vee/examples
